version: '3.7'
services:
  app:
    image: ${APP_SVR_IMAGE}
    ports:
      - 81:80
      - 443:443
    environment:
      - ASPNETCORE_URLS=https://+;http://+ 
      - ASPNETCORE_HTTPS_PORT=443 
      - ASPNETCORE_HTTP_PORT=81
      - ASPNETCORE_Kestrel__Certificates__Default__Password=${SSL_PASSWORD}
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/SSL.pfx
      - ASPNETCORE_Environment=Development
      - DATA_SERVER_ADDR=data
      
    volumes:
      - type: bind
        source: ${SSL_SOURCE}
        target: /https/