FROM mcr.microsoft.com/dotnet/core/sdk:5.0 as builder
WORKDIR /app

COPY ./ApplicationServer/IdentityServer.csproj ./Server/IdentityServer.csproj
WORKDIR ./Server
RUN dotnet restore
COPY ./IdentityServer .
RUN dotnet publish -c Release -o out

FROM mcr.microsoft.com/dotnet/core/aspnet:5.0
ENV ASPNETCORE_ENVIRONMENT Production
ENV ASPNETCORE_URLS http://+
ENV ASPNETCORE_HTTP_PORT 81
WORKDIR /app
COPY --from=builder /app/Server/out ./Server/
WORKDIR ./Server
CMD dotnet IdentityServer.dll
