version: '3.7'
services:
  app:
    image: ${APP_SVR_IMAGE}
    deploy:
      replicas: 5
    ports:
      - 80:80
      - 443:443
    environment:
      - ASPNETCORE_URLS=https://+;http://+ 
      - ASPNETCORE_HTTPS_PORT=443 
      - ASPNETCORE_HTTP_PORT=80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=${SSL_PWD}
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/certificate.pfx
      - ASPNETCORE_Environment=Production
    volumes:
      - type: bind
        source: ${SSL_LOCATION}
        target: /https